---
# check interval in seconds
interval: 10
debug: false
sites:
  Random String:
    url: https://www.random.org/strings/?num=10&len=10&digits=on&unique=on&format=html&rnd=new
    recipient: onlyreply@example.com
    diff: true
    template: "There is another random string available: {{ .Diff }}"
  Google Banner:
    url: https://www.google.com
    recipient: onlyreply@example.com
    selector: .hplogo
    template: Seems that google has a new banner

