---
# check interval in seconds
interval: 10
debug: false
sites:
  Random String:
    url: https://www.random.org/strings/?num=10&len=10&digits=on&unique=on&format=html&rnd=new
    recipient: onlyreply@example.com
    template: There is another random string available
